// Generated by https://quicktype.io

export interface TopLevelPost {
    id:        number;
    name:      string;
    image:     string;
    attack:    number;
    defense:   number;
    hp:        number;
    type:      string;
    id_author: number;
  
}

export type LoadCrud= boolean
export type PokePopMessage= {
    Visible:boolean,
    Message:string
}
